export enum ActionType {
  ADD_TODO = 'ADD_TODO',
  COMPLETE_TODO = 'COMPLETE_TODO',
  EDIT_TODO = 'EDIT_TODO',
  DELETE_TODO = 'DELETE_TODO',
  DELETE_ALL_TODOS = 'DELETE_ALL_TODOS',
  DELETE_DONE_TODOS = 'DELETE_DONE_TODOS',
  SET_FILTER = 'SET_FILTER',
}
