export const CHANGE_THEME = "CHANGE_THEME";

export enum UsersActionType {
  FETCH_USERS = "FETCH_USERS",
  FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS",
  CARDS_LIMIT = "CARDS_LIMIT",
}

export enum PostsActionType {
  FETCH_POSTS = "FETCH_POSTS",
  FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_LIMIT = "FETCH_POSTS_LIMIT",
}

export enum PostDetailsActionType {
  FETCH_POSTS_DETAILS = "FETCH_POSTS_DETAILS",
  FETCH_POSTS_DETAILS_SUCCESS = "FETCH_POSTS_DETAILS_SUCCESS",
  FETCH_POSTS_COMMENTS = "FETCH_POSTS_COMMENTS",
  FETCH_POSTS_COMMENTS_SUCCESS = "FETCH_POSTS_COMMENTS_SUCCESS",
  FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR",
}
